version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: utm_postgres
    environment:
      POSTGRES_DB: utm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    # command: ["/mediamtx", "/mediamtx.yml"]
    ports:
      - "1935:1935" # RTMP
      - "8554:8554" # RTSP
      - "9997:9997" # HTTP-API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:Z
    restart: unless-stopped

  backend:
    build: ./server
    container_name: utm_backend
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=utm_db
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - MEDIAMTX_API_URL=http://mediamtx:9997
      - MEDIAMTX_HOST=mediamtx
    depends_on:
      - postgres
      - mediamtx
    volumes:
      - ./server:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  postgres_data:
