version: "3.8"
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    command: ["/mediamtx", "/mediamtx.yml"]
    ports:
      - "1935:1935"   # RTMP
      - "8554:8554"   # RTSP
      - "9997:9997"   # HTTP-API
    volumes:
      - ./mediamtx.yml:/mediamtx.yml:Z
    restart: unless-stopped
